export const ELECTRON_CHANNELS = {
  appendStoreRecords: "masthead:store:append",
  clearLocalData: "masthead:store:clear",
  exportStoreRecords: "masthead:store:export",
  mcpLaunchConfig: "masthead:mcp:launch-config",
  mcpValidateLaunchConfig: "masthead:mcp:validate-launch-config",
  openDataDirectory: "masthead:data:open-directory",
  pruneLocalData: "masthead:store:prune",
  readStoreRecords: "masthead:store:read",
  rendererConfig: "masthead:renderer:config",
  startLiveConnector: "masthead:connector:start",
  setKeepRunningInTray: "masthead:window:set-keep-running-in-tray",
  windowClose: "masthead:window:close",
  windowMaximize: "masthead:window:maximize",
  windowMinimize: "masthead:window:minimize",
  notifySessionTransition: "masthead:notify:session-transition",
  mastheadPagesGetConnection: "masthead:pages:get-connection",
  mastheadPagesConnect: "masthead:pages:connect",
  mastheadPagesDisconnect: "masthead:pages:disconnect",
  mastheadPagesListLogbooks: "masthead:pages:list-logbooks",
  mastheadPagesCreateLogbook: "masthead:pages:create-logbook",
  mastheadPagesChooseCover: "masthead:pages:choose-cover",
  mastheadPagesClearCover: "masthead:pages:clear-cover",
  mastheadPagesUploadCover: "masthead:pages:upload-cover",
  mastheadPagesPublishStaged: "masthead:pages:publish-staged",
  mastheadPagesRemoveStaged: "masthead:pages:remove-staged"
} as const;

export const LEGACY_COMMAND_TO_CHANNEL: Record<string, ElectronChannel> = {
  append_store_records_command: ELECTRON_CHANNELS.appendStoreRecords,
  clear_local_data_command: ELECTRON_CHANNELS.clearLocalData,
  export_store_records_command: ELECTRON_CHANNELS.exportStoreRecords,
  mcp_launch_config_command: ELECTRON_CHANNELS.mcpLaunchConfig,
  mcp_validate_launch_config_command: ELECTRON_CHANNELS.mcpValidateLaunchConfig,
  open_data_directory_command: ELECTRON_CHANNELS.openDataDirectory,
  prune_local_data_command: ELECTRON_CHANNELS.pruneLocalData,
  read_store_records_command: ELECTRON_CHANNELS.readStoreRecords,
  start_live_connector_command: ELECTRON_CHANNELS.startLiveConnector,
  set_keep_running_in_tray_command: ELECTRON_CHANNELS.setKeepRunningInTray,
  window_close_command: ELECTRON_CHANNELS.windowClose,
  window_maximize_command: ELECTRON_CHANNELS.windowMaximize,
  window_minimize_command: ELECTRON_CHANNELS.windowMinimize,
  notify_session_transition_command: ELECTRON_CHANNELS.notifySessionTransition,
  masthead_pages_get_connection_command: ELECTRON_CHANNELS.mastheadPagesGetConnection,
  masthead_pages_connect_command: ELECTRON_CHANNELS.mastheadPagesConnect,
  masthead_pages_disconnect_command: ELECTRON_CHANNELS.mastheadPagesDisconnect,
  masthead_pages_list_logbooks_command: ELECTRON_CHANNELS.mastheadPagesListLogbooks,
  masthead_pages_create_logbook_command: ELECTRON_CHANNELS.mastheadPagesCreateLogbook,
  masthead_pages_choose_cover_command: ELECTRON_CHANNELS.mastheadPagesChooseCover,
  masthead_pages_clear_cover_command: ELECTRON_CHANNELS.mastheadPagesClearCover,
  masthead_pages_upload_cover_command: ELECTRON_CHANNELS.mastheadPagesUploadCover,
  masthead_pages_publish_staged_command: ELECTRON_CHANNELS.mastheadPagesPublishStaged,
  masthead_pages_remove_staged_command: ELECTRON_CHANNELS.mastheadPagesRemoveStaged
};

export type ElectronChannel = (typeof ELECTRON_CHANNELS)[keyof typeof ELECTRON_CHANNELS];
