import {
  ArrowRight,
  BookOpenText,
  Brain,
  CalendarBlank,
  CaretDown,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretLeft,
  CaretRight,
  ChartLineUp,
  CirclesThree,
  Clock,
  ClockCounterClockwise,
  Cpu,
  Database,
  FileMagnifyingGlass,
  FolderOpen,
  Gauge,
  GearSix,
  GitBranch,
  LockSimple,
  MagnifyingGlass,
  PauseCircle,
  PlugsConnected,
  Pulse,
  ShieldCheck,
  SquaresFour,
  TerminalWindow,
  Timer,
  TrendUp,
  Warning,
  X,
  type Icon as PhosphorIcon
} from "@phosphor-icons/react";

export const iconRegistry = {
  sessions: Pulse,
  models: Cpu,
  alerts: Warning,
  logbook: BookOpenText,
  performance: ChartLineUp,
  sources: Database,
  usage: Gauge,
  agentAccess: ShieldCheck,
  settings: GearSix,

  search: MagnifyingGlass,
  harness: PlugsConnected,
  lifecycle: CirclesThree,
  recentActivity: ClockCounterClockwise,
  timeRange: CalendarBlank,
  project: FolderOpen,
  fileSearch: FileMagnifyingGlass,
  refreshInterval: Timer,
  changeLayout: SquaresFour,

  runtime: Clock,
  model: Cpu,
  worktree: GitBranch,
  thinking: Brain,
  source: TerminalWindow,
  startedAt: CalendarBlank,
  lastActivity: ClockCounterClockwise,

  active: Pulse,
  idle: PauseCircle,
  blocked: LockSimple,

  selectChevron: CaretDown,
  pageFirst: CaretDoubleLeft,
  pagePrevious: CaretLeft,
  pageNext: CaretRight,
  pageLast: CaretDoubleRight,
  trendUp: TrendUp,
  close: X,
  arrowRight: ArrowRight
} satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof iconRegistry;
